import { useState } from 'react';
import { useMutation, useQuery } from '@apollo/client';
import { Heart, MapPin, ShieldCheck, Star } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { ADD_REVIEW, GET_PROPERTY, GET_REVIEWS, REQUEST_BOOKING, TOGGLE_FAVORITE } from '../graphql/operations.js';

export default function PropertyDetails(){
 const {id}=useParams(); const [message,setMessage]=useState(''); const [notice,setNotice]=useState(''); const [review,setReview]=useState({rating:'5',comment:''});
 const {loading,error,data}=useQuery(GET_PROPERTY,{variables:{id}}); const reviewsQuery=useQuery(GET_REVIEWS,{variables:{propertyId:id}}); const [toggleFavorite]=useMutation(TOGGLE_FAVORITE); const [requestBooking,bookingState]=useMutation(REQUEST_BOOKING); const [addReview,reviewState]=useMutation(ADD_REVIEW,{refetchQueries:[{query:GET_REVIEWS,variables:{propertyId:id}}]});
 if(loading)return <main className="empty-page"><p>Loading home...</p></main>; if(error||!data?.property)return <main className="empty-page"><div><h1>Home not found</h1><Link to="/properties">Back to homes</Link></div></main>; const property=data.property;
 async function saveFavorite(){if(!localStorage.getItem('shenest_token'))return setNotice('Please log in before saving a home.');try{const result=await toggleFavorite({variables:{propertyId:property.id}});setNotice(result.data.toggleFavorite?'Saved to your favorites.':'Removed from your favorites.')}catch(e){setNotice(e.message)}}
 async function submitBooking(e){e.preventDefault();if(!localStorage.getItem('shenest_token'))return setNotice('Please log in before sending a booking request.');try{await requestBooking({variables:{propertyId:property.id,message:message||null}});setMessage('');setNotice('Booking request sent to the landlord.')}catch(err){setNotice(err.message)}}
 async function submitReview(e){e.preventDefault();if(!localStorage.getItem('shenest_token'))return setNotice('Please log in before leaving a review.');try{await addReview({variables:{propertyId:id,rating:Number(review.rating),comment:review.comment||null}});setReview({rating:'5',comment:''});setNotice('Thanks for sharing your review.')}catch(err){setNotice(err.message)}}
 const reviews=reviewsQuery.data?.propertyReviews??[];
 return <main className="details-page section"><Link className="back-link" to="/properties">← Back to homes</Link><div className="details-layout"><div><img className="details-image" src={property.image||'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80'} alt={property.title}/><div className="details-copy"><div className="details-title-row"><div><h1>{property.title}</h1><p><MapPin size={16}/>{property.location}</p></div>{property.verified&&<span className="verified"><ShieldCheck size={17}/>Verified</span>}</div><p className="details-description">{property.description}</p><div className="details-meta"><span>{property.type}</span><strong>₦{property.price.toLocaleString()} / year</strong></div></div><section className="reviews-section"><h2>Reviews</h2><form className="review-form" onSubmit={submitReview}><select value={review.rating} onChange={e=>setReview({...review,rating:e.target.value})}><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select><input value={review.comment} onChange={e=>setReview({...review,comment:e.target.value})} placeholder="Share your experience"/><button className="button small" disabled={reviewState.loading}>Post</button></form><div className="review-list">{reviews.length===0?<p>No reviews yet.</p>:reviews.map(item=><article key={item.id}><span><Star size={15}/> {item.rating}/5</span><p>{item.comment||'No written comment.'}</p></article>)}</div></section></div><aside className="booking-card"><h2>Interested in this home?</h2><p>Send a simple booking request. The landlord can review it before anything is confirmed.</p><button className="outline-button full" type="button" onClick={saveFavorite}><Heart size={17}/>Save favorite</button><form onSubmit={submitBooking}><label>Message to landlord<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Hi, I am interested in this home..." rows="5"/></label><button className="button full" disabled={bookingState.loading}>{bookingState.loading?'Sending...':'Request booking'}</button></form>{notice&&<p className="form-message">{notice}</p>}</aside></div></main>
}
